workflows:
  expo-android:
    name: Expo Android Build

    environment:
      node: latest

    scripts:
      - npm install
      - npx expo export

    artifacts:
      - dist/**

    publishing:
      email:
        recipients:
          - robert.rosenberger99@gmail.com
